export const genres = [
  { label: 'American', value: 'American' },
  { label: 'Asian', value: 'Asian' },
  { label: 'Bakery', value: 'Bakery' },
  { label: 'Belgian', value: 'Belgian' },
  { label: 'Bistro', value: 'Bistro' },
  { label: 'British', value: 'British' },
  { label: 'Cafe', value: 'Cafe' },
  { label: 'Coffee', value: 'Coffee' },
  { label: 'Contemporary', value: 'Contemporary' },
  { label: 'Continental', value: 'Continental' },
  { label: 'Eclectic', value: 'Eclectic' },
  { label: 'European', value: 'European' },
  { label: 'French', value: 'French' },
  { label: 'Fusion', value: 'Fusion' },
  { label: 'Grill', value: 'Grill' },
  { label: 'Hawaiian', value: 'Hawaiian' },
  { label: 'International', value: 'International' },
  { label: 'Irish', value: 'Irish' },
  { label: 'Italian', value: 'Italian' },
  { label: 'Japanese', value: 'Japanese' },
  { label: 'Kosher', value: 'Kosher' },
  { label: 'Oysters', value: 'Oysters' },
  { label: 'Pacific Rim', value: 'Pacific Rim' },
  { label: 'Pasta', value: 'Pasta' },
  { label: 'Polynesian', value: 'Polynesian' },
  { label: 'Sandwiches', value: 'Sandwiches' },
  { label: 'Seafood', value: 'Seafood' },
  { label: 'Steak', value: 'Steak' },
  { label: 'Sushi', value: 'Sushi' },
  { label: 'Tea', value: 'Tea' },
  { label: 'Traditional', value: 'Traditional' },
  { label: 'Vegetarian', value: 'Vegetarian' },
  { label: 'Vietnamese', value: 'Vietnamese' },
];
